version: '3'

services:
  fast-api:
    ports:
      - 8000:8000
    build: ./
    restart: always
    volumes:
      - ../:/code
    command: >
      bash -c "uvicorn app.main:app --reload --host 0.0.0.0"
    ports:
      - "8000:8000"
