version: '3'

services:
  fast-api:
    ports:
      - 8000:8000
    build: ./
    restart: always
    volumes:
      - ../:/code
    depends_on:
      - elasticsearch
    command: >
      bash -c "python app/build_index.py && uvicorn app.main:app --reload --host 0.0.0.0"
    ports:
      - "8000:8000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - "9200:9200"
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    tty: true
    environment:
      discovery.type: single-node
